appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: KFbnG9ktDuUY4aAuLMv7skM6imzuJTlIq7BD+bFJ9h3rEdO0Tj3r3QOfj4KZjYd8v5M+F1S4GQgQlbS2QpppT7KLDYqiOhw6VO+w8UEpTDVUjKUbIR/bhwdkhke+zQ6m9dyPzH/Z70Ji/qHfBs7Bnbs0/FAQFoACWRMM2FBtaoU+r+Wk4HXvMdKhK20sprcWq0I6ojqt0EOt4Koh2yMwEkXbgm/ua5/XbIcmkk/JNI6NT0SMHuHmw3dkor1g92ApbhlIrNpXT/vNnlORFL41z5SLzqweUFhed8AWF6RP89w1AjGwY94X4TJrbsoET2s2bYCFlJdRTjhKG/GdQGBXQXHHQiqeSZXsCmlzQbziEzVh7BOA0ms3WazRC3bSxamvubvvghSk28usWroSP39GlBwRxt87/k4s7awEL9Itv08huRv4EcJpCUr6yMD1nKZf2AlMuctX4e57HFLLLnrzfPjaPO83fNQj3srAZln0+Co7cDnaGFYg4XANYmJLo38iL3jroJWR8p80gx2J11u4QlasgLoWLj/ewHfDWuDyYFlvB36hRK28j4tN5nl4myKsT9E/i4JR26byNgWRX4DchyWoNqlSLPgw6UVGWotZkpShGWGIgkiF22qpFP/2CpO2QlByeD5PtUKfX6KefEPaqQ5LM1qo7wylxXwtcsFDV9Y=}
